version: 2
refrences:
  ignored-branches: &ignored-branches
     branches:
      ignore:
        - gh-pages

  cache-options: &cache-options
    key: package-cache-{{ checksum "package.json" }}

jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          <<: *cache-options
      - run:
          name: npm-install
          command: npm install
      - save_cache:
          <<: *cache-options
          paths:
            - ./node_modules
  deploy:
    docker:
      - image: circleci/node:12
    steps:
      - add_ssh_keys:
          fingerprints:
            - "66:43:b6:89:39:c7:9e:61:bf:39:cb:22:46:0b:88:a5"
      - checkout
      - restore_cache:
          <<: *cache-options
      - run:
          name: deploy-gh-pages
          command: ./bin/deploy


workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            <<: *ignored-branches
      - deploy:
          filters:
            branches:
              only:
                - develop